//! What starts at login: Hyprland autostart (Omarchy's, yours, and the items this
//! app manages), XDG autostart entries, and systemd user services.
//!
//! We never rewrite the user's own Hyprland files. Items added here live in our
//! state file and are generated into `~/.config/hypr/tasks.lua`. XDG entries are
//! turned off the standard way: a `Hidden=true` copy in `~/.config/autostart`.

use crate::{apps, cmd, paths};
use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::path::{Path, PathBuf};

// ---------- Hyprland ----------

#[derive(Debug, Clone, PartialEq)]
pub struct HyprEntry {
    pub command: String,
    /// Wrapped in `uwsm-app` (launched as an app, not a raw command).
    pub launched: bool,
}

fn lua_string(s: &str) -> Option<(String, &str)> {
    let s = s.trim_start();
    let quote = s.chars().next().filter(|c| *c == '"' || *c == '\'')?;
    let mut out = String::new();
    let mut chars = s[1..].char_indices();
    while let Some((i, c)) = chars.next() {
        if c == '\\' {
            if let Some((_, n)) = chars.next() {
                out.push(match n {
                    'n' => '\n',
                    't' => '\t',
                    other => other,
                });
            }
        } else if c == quote {
            return Some((out, &s[1 + i + 1..]));
        } else {
            out.push(c);
        }
    }
    None
}

/// Commands started by a Lua autostart file (`o.launch_on_start`, `o.exec_on_start`,
/// `hl.exec_cmd`, including `hl.exec_cmd(o.launch(...))`). Commented lines are skipped.
pub fn parse_autostart_lua(text: &str) -> Vec<HyprEntry> {
    let mut out = Vec::new();
    for line in text.lines() {
        let line = line.trim();
        if line.starts_with("--") {
            continue;
        }
        let patterns: [(&str, bool); 5] = [
            ("o.launch_on_start(", true),
            ("o.exec_on_start(", false),
            ("hl.exec_cmd(o.launch(", true),
            ("hl.exec_cmd(", false),
            ("exec-once =", false),
        ];
        for (pat, launched) in patterns {
            let Some(i) = line.find(pat) else { continue };
            let rest = &line[i + pat.len()..];
            let command = if pat == "exec-once =" { Some(rest.trim().to_string()) } else { lua_string(rest).map(|(s, _)| s) };
            if let Some(command) = command.filter(|c| !c.is_empty()) {
                out.push(HyprEntry { command, launched });
            }
            break;
        }
    }
    out
}

pub fn omarchy_entries() -> Vec<HyprEntry> {
    parse_autostart_lua(&std::fs::read_to_string(paths::omarchy_autostart_lua()).unwrap_or_default())
}

pub fn user_entries() -> Vec<HyprEntry> {
    parse_autostart_lua(&std::fs::read_to_string(paths::user_autostart_lua()).unwrap_or_default())
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Managed {
    pub name: String,
    pub command: String,
    pub enabled: bool,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct State {
    pub hyprland: Vec<Managed>,
}

pub fn load() -> State {
    std::fs::read_to_string(paths::state_file()).ok().and_then(|t| serde_json::from_str(&t).ok()).unwrap_or_default()
}

fn lua_quote(s: &str) -> String {
    format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\""))
}

pub fn generate(state: &State) -> String {
    let mut out = String::from(
        "-- Generated by Tasks (Startup page). Edits here are replaced; change items in Tasks.\n\
         -- Loaded from hyprland.lua with: require(\"hypr.tasks\")\n",
    );
    for m in &state.hyprland {
        let line = format!("o.launch_on_start({})", lua_quote(&m.command));
        if m.enabled {
            out.push_str(&format!("{line} -- {}\n", m.name.replace('\n', " ")));
        } else {
            out.push_str(&format!("-- off: {line} -- {}\n", m.name.replace('\n', " ")));
        }
    }
    out
}

/// Save our state and regenerate `tasks.lua`.
pub fn save(state: &State) -> Result<()> {
    cmd::atomic_write(&paths::state_file(), &serde_json::to_string_pretty(state)?)?;
    cmd::atomic_write(&paths::managed_lua(), &generate(state))?;
    Ok(())
}

/// Whether hyprland.lua loads our file.
pub fn included() -> bool {
    std::fs::read_to_string(paths::hyprland_lua())
        .map(|t| t.lines().any(|l| !l.trim_start().starts_with("--") && l.contains("hypr.tasks")))
        .unwrap_or(false)
}

/// Append the one `require` line to hyprland.lua, after a backup. Only on request.
pub fn add_include() -> Result<PathBuf> {
    let path = paths::hyprland_lua();
    let text = std::fs::read_to_string(&path).context("could not read hyprland.lua")?;
    let stamp = std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).map(|d| d.as_secs()).unwrap_or(0);
    let backup = path.with_file_name(format!("hyprland.lua.tasks-bak.{stamp}"));
    std::fs::write(&backup, &text)?;
    let mut new = text.trim_end().to_string();
    new.push_str("\n\nrequire(\"hypr.tasks\") -- Tasks app (startup items)\n");
    cmd::atomic_write(&path, &new)?;
    Ok(backup)
}

// ---------- XDG autostart ----------

#[derive(Debug, Clone, Default)]
pub struct XdgEntry {
    pub id: String,
    pub name: String,
    pub comment: String,
    pub exec: String,
    pub icon: String,
    pub enabled: bool,
    /// The system provides it (a user copy may override it).
    pub system: bool,
    pub user_file: Option<PathBuf>,
    /// Excluded from Hyprland sessions by OnlyShowIn/NotShowIn.
    pub other_desktop: bool,
}

fn desktop_excluded(kv: &HashMap<String, String>, desktop: &str) -> bool {
    let list =
        |k: &str| kv.get(k).map(|v| v.split(';').map(|s| s.trim().to_lowercase()).filter(|s| !s.is_empty()).collect::<Vec<_>>());
    let d = desktop.to_lowercase();
    if let Some(only) = list("OnlyShowIn") {
        return !only.iter().any(|x| d.split(':').any(|p| p == x));
    }
    if let Some(not) = list("NotShowIn") {
        return not.iter().any(|x| d.split(':').any(|p| p == x));
    }
    false
}

fn entry_enabled(kv: &HashMap<String, String>) -> bool {
    kv.get("Hidden").is_none_or(|v| v != "true") && kv.get("X-GNOME-Autostart-enabled").is_none_or(|v| v != "false")
}

fn read_dir_desktops(dir: &Path) -> Vec<(String, PathBuf)> {
    let Ok(d) = std::fs::read_dir(dir) else { return vec![] };
    d.flatten()
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|x| x == "desktop"))
        .filter_map(|p| Some((p.file_stem()?.to_string_lossy().to_string(), p)))
        .collect()
}

pub fn xdg_entries() -> Vec<XdgEntry> {
    let desktop = std::env::var("XDG_CURRENT_DESKTOP").unwrap_or_else(|_| "Hyprland".into());
    let system: HashMap<String, PathBuf> = read_dir_desktops(&paths::system_xdg_autostart()).into_iter().collect();
    let user: HashMap<String, PathBuf> = read_dir_desktops(&paths::user_xdg_autostart()).into_iter().collect();
    let mut ids: Vec<&String> = system.keys().chain(user.keys()).collect();
    ids.sort();
    ids.dedup();
    let mut out = Vec::new();
    for id in ids {
        let path = user.get(id).or_else(|| system.get(id)).expect("id from one of the maps");
        let kv = apps::parse_desktop(&std::fs::read_to_string(path).unwrap_or_default());
        // A Hidden=true override hides the name; fall back to the system file for display.
        let sys_kv = system.get(id).map(|p| apps::parse_desktop(&std::fs::read_to_string(p).unwrap_or_default()));
        let pick = |k: &str| kv.get(k).or_else(|| sys_kv.as_ref().and_then(|s| s.get(k))).cloned().unwrap_or_default();
        let name = pick("Name");
        out.push(XdgEntry {
            id: id.clone(),
            name: if name.is_empty() { id.clone() } else { name },
            comment: pick("Comment"),
            exec: pick("Exec"),
            icon: pick("Icon"),
            enabled: entry_enabled(&kv),
            system: system.contains_key(id),
            user_file: user.get(id).cloned(),
            other_desktop: desktop_excluded(sys_kv.as_ref().unwrap_or(&kv), &desktop),
        });
    }
    out.sort_by_key(|e| (e.other_desktop, e.name.to_lowercase()));
    out
}

/// Set (or add) one key in the `[Desktop Entry]` group of desktop-file text.
pub fn set_desktop_key(text: &str, key: &str, value: &str) -> String {
    let mut out = Vec::new();
    let mut in_entry = false;
    let mut done = false;
    for line in text.lines() {
        let t = line.trim();
        if t.starts_with('[') {
            if in_entry && !done {
                out.push(format!("{key}={value}"));
                done = true;
            }
            in_entry = t == "[Desktop Entry]";
        } else if in_entry && t.split_once('=').is_some_and(|(k, _)| k.trim() == key) {
            if !done {
                out.push(format!("{key}={value}"));
                done = true;
            }
            continue;
        }
        out.push(line.to_string());
    }
    if !done {
        if !text.lines().any(|l| l.trim() == "[Desktop Entry]") {
            out.insert(0, "[Desktop Entry]".into());
        }
        // Insert right after the group header's block (end of group = end of file here).
        let pos = out
            .iter()
            .enumerate()
            .skip_while(|(_, l)| l.trim() != "[Desktop Entry]")
            .skip(1)
            .find(|(_, l)| l.trim().starts_with('['))
            .map(|(i, _)| i)
            .unwrap_or(out.len());
        out.insert(pos, format!("{key}={value}"));
    }
    let mut s = out.join("\n");
    s.push('\n');
    s
}

/// Turn an XDG entry on or off. System entries get a user override; the system
/// file is never touched.
pub fn set_xdg_enabled(e: &XdgEntry, on: bool) -> Result<()> {
    let target = paths::user_xdg_autostart().join(format!("{}.desktop", e.id));
    let source = if target.exists() { target.clone() } else { paths::system_xdg_autostart().join(format!("{}.desktop", e.id)) };
    let text = std::fs::read_to_string(&source).with_context(|| format!("could not read {}", source.display()))?;
    let mut new = set_desktop_key(&text, "Hidden", if on { "false" } else { "true" });
    if on && new.contains("X-GNOME-Autostart-enabled=false") {
        new = set_desktop_key(&new, "X-GNOME-Autostart-enabled", "true");
    }
    cmd::atomic_write(&target, &new)
}

/// Remove a user entry, or the user override of a system one (restoring the default).
pub fn remove_user_xdg(e: &XdgEntry) -> Result<()> {
    if let Some(p) = &e.user_file {
        std::fs::remove_file(p)?;
    }
    Ok(())
}

/// Add an app to XDG autostart by copying its desktop file.
pub fn add_xdg(app: &apps::App) -> Result<()> {
    let text = std::fs::read_to_string(&app.path)?;
    let id = if app.id.is_empty() { "tasks-item".to_string() } else { app.id.clone() };
    cmd::atomic_write(&paths::user_xdg_autostart().join(format!("{id}.desktop")), &set_desktop_key(&text, "Hidden", "false"))
}

/// The systemd unit uwsm/systemd-xdg-autostart-generator creates for an entry.
pub fn xdg_unit(id: &str) -> String {
    format!("app-{}@autostart.service", systemd_escape(id))
}

pub fn systemd_escape(s: &str) -> String {
    let mut out = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_ascii_alphanumeric() || c == '_' || c == ':' || (c == '.' && i > 0) {
            out.push(c);
        } else if c == '/' {
            out.push('-');
        } else {
            let mut buf = [0u8; 4];
            for b in c.encode_utf8(&mut buf).bytes() {
                out.push_str(&format!("\\x{b:02x}"));
            }
        }
    }
    out
}

/// Undo systemd's `\xNN` escaping for display ("gnome\x2dkeyring" -> "gnome-keyring").
pub fn unescape(s: &str) -> String {
    let mut bytes = Vec::new();
    let b = s.as_bytes();
    let mut i = 0;
    while i < b.len() {
        if b[i] == b'\\'
            && b.get(i + 1) == Some(&b'x')
            && let Some(v) = s.get(i + 2..i + 4).and_then(|h| u8::from_str_radix(h, 16).ok())
        {
            bytes.push(v);
            i += 4;
            continue;
        }
        bytes.push(b[i]);
        i += 1;
    }
    String::from_utf8_lossy(&bytes).to_string()
}

// ---------- systemd ----------

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Unit {
    pub name: String,
    pub description: String,
    pub active: String,
    pub sub: String,
    /// enabled, disabled, static, generated, masked…
    pub file_state: String,
}

impl Unit {
    pub fn running(&self) -> bool {
        self.active == "active"
    }
    pub fn failed(&self) -> bool {
        self.active == "failed"
    }
}

/// `systemctl [--user] list-units/list-unit-files -o json` merged by unit name.
pub fn parse_units(units_json: &str, files_json: &str) -> Vec<Unit> {
    let parse = |t: &str| serde_json::from_str::<Vec<serde_json::Value>>(t).unwrap_or_default();
    let mut map: HashMap<String, Unit> = HashMap::new();
    for u in parse(units_json) {
        let Some(name) = u["unit"].as_str() else { continue };
        if u["load"].as_str() == Some("not-found") {
            continue;
        }
        map.insert(
            name.to_string(),
            Unit {
                name: name.to_string(),
                description: u["description"].as_str().unwrap_or("").to_string(),
                active: u["active"].as_str().unwrap_or("").to_string(),
                sub: u["sub"].as_str().unwrap_or("").to_string(),
                file_state: String::new(),
            },
        );
    }
    for f in parse(files_json) {
        let Some(name) = f["unit_file"].as_str() else { continue };
        // Templates (foo@.service) can't run by themselves.
        if name.ends_with("@.service") || name.ends_with("@.timer") {
            continue;
        }
        let e = map.entry(name.to_string()).or_insert_with(|| Unit {
            name: name.to_string(),
            active: "inactive".into(),
            sub: "dead".into(),
            ..Default::default()
        });
        e.file_state = f["state"].as_str().unwrap_or("").to_string();
    }
    let mut out: Vec<Unit> = map.into_values().collect();
    out.sort_by(|a, b| a.name.cmp(&b.name));
    out
}

pub fn units(user: bool) -> Vec<Unit> {
    let scope = if user { "--user" } else { "--system" };
    let units = cmd::output(&["systemctl", scope, "list-units", "--type=service", "--all", "-o", "json", "--no-pager"])
        .unwrap_or_default();
    let files =
        cmd::output(&["systemctl", scope, "list-unit-files", "--type=service", "-o", "json", "--no-pager"]).unwrap_or_default();
    parse_units(&units, &files)
}

/// A systemd timer: its own unit state, plus when it fires.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct Timer {
    pub unit: Unit,
    /// The unit it starts.
    pub activates: String,
    /// Next and last run, as Unix seconds.
    pub next: Option<f64>,
    pub last: Option<f64>,
}

/// `systemctl list-timers -o json` merged into the timer units.
pub fn parse_timers(timers_json: &str, units: Vec<Unit>) -> Vec<Timer> {
    let list = serde_json::from_str::<Vec<serde_json::Value>>(timers_json).unwrap_or_default();
    // Microseconds since the epoch; 0 or null means never.
    let when = |v: &serde_json::Value| v.as_f64().filter(|t| *t > 0.0).map(|t| t / 1e6);
    let info: HashMap<&str, &serde_json::Value> = list.iter().filter_map(|t| Some((t["unit"].as_str()?, t))).collect();
    units
        .into_iter()
        .map(|unit| {
            let t = info.get(unit.name.as_str());
            Timer {
                activates: t
                    .and_then(|t| t["activates"].as_str())
                    .map(String::from)
                    .unwrap_or_else(|| unit.name.trim_end_matches(".timer").to_string() + ".service"),
                next: t.and_then(|t| when(&t["next"])),
                last: t.and_then(|t| when(&t["last"])),
                unit,
            }
        })
        .collect()
}

pub fn timers(user: bool) -> Vec<Timer> {
    let scope = if user { "--user" } else { "--system" };
    let run = |args: &[&str]| {
        cmd::output(&[&["systemctl", scope][..], args, &["-o", "json", "--no-pager"]].concat()).unwrap_or_default()
    };
    let units = parse_units(&run(&["list-units", "--type=timer", "--all"]), &run(&["list-unit-files", "--type=timer"]));
    parse_timers(&run(&["list-timers", "--all"]), units)
}

/// `systemctl show -p …` as key/value pairs.
pub fn unit_props(unit: &str, user: bool) -> HashMap<String, String> {
    let scope = if user { "--user" } else { "--system" };
    let props = "MainPID,MemoryCurrent,CPUUsageNSec,ActiveEnterTimestamp,FragmentPath,Restart,ExecStart,ActiveState,SubState";
    let text = cmd::output(&["systemctl", scope, "show", unit, "-p", props, "--no-pager"]).unwrap_or_default();
    parse_props(&text)
}

pub fn parse_props(text: &str) -> HashMap<String, String> {
    text.lines().filter_map(|l| l.split_once('=')).map(|(k, v)| (k.to_string(), v.to_string())).collect()
}

/// `systemd-analyze blame` as seconds per unit.
pub fn parse_blame(text: &str) -> HashMap<String, f64> {
    text.lines()
        .filter_map(|l| {
            let mut parts: Vec<&str> = l.split_whitespace().collect();
            let unit = parts.pop()?.to_string();
            let mut secs = 0.0;
            for p in parts {
                let (num, mult) = if let Some(v) = p.strip_suffix("ms") {
                    (v, 0.001)
                } else if let Some(v) = p.strip_suffix("min") {
                    (v, 60.0)
                } else if let Some(v) = p.strip_suffix("us") {
                    (v, 0.000001)
                } else if let Some(v) = p.strip_suffix('s') {
                    (v, 1.0)
                } else {
                    (p.strip_suffix('h')?, 3600.0)
                };
                secs += num.parse::<f64>().ok()? * mult;
            }
            Some((unit, secs))
        })
        .collect()
}

pub fn blame(user: bool) -> HashMap<String, f64> {
    let scope = if user { "--user" } else { "--system" };
    parse_blame(&cmd::output(&["systemd-analyze", scope, "blame", "--no-pager"]).unwrap_or_default())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_lua_autostart() {
        let text = r#"
hl.on("hyprland.start", function()
  hl.exec_cmd("omarchy-launch-shell")
  hl.exec_cmd(o.launch("udiskie --automount --no-notify"))
end)
-- o.launch_on_start("commented")
o.launch_on_start("signal-desktop")
o.exec_on_start('say "hi"')
"#;
        let e = parse_autostart_lua(text);
        assert_eq!(e.len(), 4);
        assert_eq!(e[0], HyprEntry { command: "omarchy-launch-shell".into(), launched: false });
        assert_eq!(e[1], HyprEntry { command: "udiskie --automount --no-notify".into(), launched: true });
        assert_eq!(e[2].command, "signal-desktop");
        assert_eq!(e[3].command, "say \"hi\"");
    }

    #[test]
    fn generates_managed_lua() {
        let s = State {
            hyprland: vec![
                Managed { name: "Chat".into(), command: "signal-desktop".into(), enabled: true },
                Managed { name: "Off".into(), command: "x \"y\"".into(), enabled: false },
            ],
        };
        let lua = generate(&s);
        assert!(lua.contains("o.launch_on_start(\"signal-desktop\") -- Chat\n"));
        assert!(lua.contains("-- off: o.launch_on_start(\"x \\\"y\\\"\")"));
        assert_eq!(parse_autostart_lua(&lua).len(), 1);
    }

    #[test]
    fn sets_hidden_key() {
        let text = "[Desktop Entry]\nName=A\nHidden=false\n[Desktop Action x]\nName=B\n";
        let out = set_desktop_key(text, "Hidden", "true");
        assert_eq!(out, "[Desktop Entry]\nName=A\nHidden=true\n[Desktop Action x]\nName=B\n");
        let out = set_desktop_key("[Desktop Entry]\nName=A\n[Desktop Action x]\nName=B\n", "Hidden", "true");
        assert_eq!(out, "[Desktop Entry]\nName=A\nHidden=true\n[Desktop Action x]\nName=B\n");
        let out = set_desktop_key("[Desktop Entry]\nName=A\n", "Hidden", "true");
        assert_eq!(out, "[Desktop Entry]\nName=A\nHidden=true\n");
    }

    #[test]
    fn respects_only_show_in() {
        let kv = apps::parse_desktop("[Desktop Entry]\nOnlyShowIn=GNOME;Unity;\n");
        assert!(desktop_excluded(&kv, "Hyprland"));
        let kv = apps::parse_desktop("[Desktop Entry]\nNotShowIn=KDE;\n");
        assert!(!desktop_excluded(&kv, "Hyprland"));
    }

    #[test]
    fn escapes_unit_names() {
        assert_eq!(xdg_unit("gnome-keyring-pkcs11"), "app-gnome\\x2dkeyring\\x2dpkcs11@autostart.service");
        assert_eq!(xdg_unit("com.onepassword.OnePassword"), "app-com.onepassword.OnePassword@autostart.service");
    }

    #[test]
    fn unescapes_units() {
        assert_eq!(unescape("app-gnome\\x2dkeyring@autostart.service"), "app-gnome-keyring@autostart.service");
        assert_eq!(unescape("plain"), "plain");
    }

    #[test]
    fn parses_timers() {
        let units = vec![
            Unit { name: "backup.timer".into(), active: "active".into(), ..Default::default() },
            Unit { name: "idle.timer".into(), ..Default::default() },
        ];
        let json = r#"[{"next":1791176995184497,"left":1,"last":null,"passed":0,"unit":"backup.timer","activates":"backup-run.service"}]"#;
        let t = parse_timers(json, units);
        assert_eq!(t[0].activates, "backup-run.service");
        assert!((t[0].next.unwrap() - 1_791_176_995.184497).abs() < 1e-3);
        assert_eq!(t[0].last, None);
        // Not listed by list-timers: guessed from its name, never runs.
        assert_eq!(t[1].activates, "idle.service");
        assert_eq!(t[1].next, None);
    }

    #[test]
    fn parses_props() {
        let p = parse_props("MainPID=42\nExecStart={ path=/usr/bin/x ; argv[]=/usr/bin/x -a }\nRestart=no\n");
        assert_eq!(p["MainPID"], "42");
        assert_eq!(p["ExecStart"], "{ path=/usr/bin/x ; argv[]=/usr/bin/x -a }");
    }

    #[test]
    fn parses_blame() {
        let b = parse_blame("2.781s wayland-session-waitenv.service\n 354ms gvfs.service\n1min 2.5s slow.service\n");
        assert!((b["wayland-session-waitenv.service"] - 2.781).abs() < 1e-9);
        assert!((b["gvfs.service"] - 0.354).abs() < 1e-9);
        assert!((b["slow.service"] - 62.5).abs() < 1e-9);
    }

    #[test]
    fn merges_units() {
        let units = r#"[{"unit":"a.service","load":"loaded","active":"active","sub":"running","description":"A"}]"#;
        let files = r#"[{"unit_file":"a.service","state":"enabled"},{"unit_file":"b.service","state":"disabled"},{"unit_file":"t@.service","state":"static"}]"#;
        let u = parse_units(units, files);
        assert_eq!(u.len(), 2);
        assert!(u[0].running());
        assert_eq!(u[0].file_state, "enabled");
        assert_eq!(u[1].active, "inactive");
    }
}
